Updated android-maven-plugin ver to the 3.9.0-rc.3
The reason is that using version 3.8.1 of
android-maven-plugin, if you compile with a maven
version 3.2.5+, the compilation of android module
fails for a:
  java.lang.NoClassDefFoundError:
  org/eclipse/aether/spi/connector/Transfer$State